spring:
  application:
    name: spring-boot-config
    description: Welcome to ${spring.application.name}

my:
 greeting: Hello world
 list:
  values: One,Two,Three
 #dbValues: "{connectionString: 'http://____', userName: 'root', password: 'pass'}"

db:
  connection: test-connection-string-here
  host: 129.0.0.1
  port: 2400

# expose all endpoints that actuator provides
management.endpoints.web.exposure.include: "*"